;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="角色所能承受的伤害量")
GameplayTagList=(Tag="Attributes.Vital.MaxHealth",DevComment="角色所能承受的最大伤害量")
GameplayTagList=(Tag="Attributes.Vital.Mana",DevComment="角色释放法术的能量源")
GameplayTagList=(Tag="Attributes.Vital.MaxMana",DevComment="角色释放法术的最大能量源")